version: "3.9"
services: 
  mongo:
    image: mongo:latest
    volumes: 
      - ./data:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
  mongo-client:
    image: mongo-express:latest
    links:
      - mongo
    ports: 
      - 8081:8081