version: '3.9'
services:
  mongo:
    image: mongo:latest
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
  mongo-client:
    image: mongo-express:latest
    environment:
      - MONGO_URL=mongodb://mongo:27017/db
    links:
      - mongo
    ports:
      - 8081:8081
